# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17MvzNo98udGbFII0Ez4J0yptIMYTK97J
"""

# scripts/evaluate_model.py

import joblib
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, roc_curve
from sklearn.model_selection import train_test_split
from preprocessing import load_and_preprocess_data

import matplotlib.pyplot as plt

def evaluate_model(filepath, model_path='models/diabetes_model.pkl'):
    X, y, _ = load_and_preprocess_data(filepath)
    model = joblib.load(model_path)

    _, X_test, _, y_test = train_test_split(X, y,
                                            test_size=0.2,
                                            stratify=y,
                                            random_state=42)

    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)[:, 1]

    print("Classification Report:\n", classification_report(y_test, y_pred))
    print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
    print("ROC-AUC Score:", roc_auc_score(y_test, y_prob))

    fpr, tpr, _ = roc_curve(y_test, y_prob)
    plt.plot(fpr, tpr, label=f"AUC = {roc_auc_score(y_test, y_prob):.2f}")
    plt.plot([0, 1], [0, 1], linestyle='--')
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate")
    plt.title("ROC Curve")
    plt.legend()
    plt.show()

if __name__ == "__main__":
    evaluate_model('data/diabetes.csv')