# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1abYr0ogOV1KPi-XtV2fbTXXdbfVddEkr
"""

# app/streamlit_app.py

import streamlit as st
import numpy as np
import joblib

# Load model and scaler
model = joblib.load('models/diabetes_model.pkl')
scaler = joblib.load('models/scaler.pkl')

st.title("🩺 Early Diabetes Risk Predictor")
st.markdown("Enter the health parameters below to predict the likelihood of diabetes:")

# Input fields
pregnancies = st.number_input("Pregnancies", min_value=0, max_value=20, value=1)
glucose = st.number_input("Glucose Level", min_value=0, max_value=300, value=120)
blood_pressure = st.number_input("Blood Pressure (mm Hg)", min_value=0, max_value=200, value=70)
skin_thickness = st.number_input("Skin Thickness (mm)", min_value=0, max_value=100, value=20)
insulin = st.number_input("Insulin (mu U/ml)", min_value=0, max_value=900, value=80)
bmi = st.number_input("BMI", min_value=0.0, max_value=70.0, value=28.0)
dpf = st.number_input("Diabetes Pedigree Function", min_value=0.0, max_value=2.5, value=0.4)
age = st.number_input("Age", min_value=1, max_value=120, value=30)

# Predict button
if st.button("Predict"):
    user_data = np.array([[pregnancies, glucose, blood_pressure, skin_thickness,
                           insulin, bmi, dpf, age]])

    # Scale user input
    user_data_scaled = scaler.transform(user_data)
    prediction = model.predict(user_data_scaled)[0]
    probability = model.predict_proba(user_data_scaled)[0][1]

    if prediction == 1:
        st.error(f"⚠️ High risk of diabetes (Probability: {probability:.2f})")
    else:
        st.success(f"✅ Low risk of diabetes (Probability: {probability:.2f})")