# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uQAo8dceNmB1AlW9zKOk7fIR7aK3Srw6
"""

# scripts/train_model.py

import joblib
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from preprocessing import load_and_preprocess_data

def train_and_save_model(filepath, model_path='models/diabetes_model.pkl'):
    X, y, scaler = load_and_preprocess_data(filepath)

    X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                        test_size=0.2,
                                                        stratify=y,
                                                        random_state=42)

    model = LogisticRegression()
    model.fit(X_train, y_train)

    # Save model and scaler
    joblib.dump(model, model_path)
    joblib.dump(scaler, 'models/scaler.pkl')

    print(f"Model trained and saved to {model_path}")

if __name__ == "__main__":
    train_and_save_model('data/diabetes.csv')